version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /.github/workflows
      - /setup-sdk
      - /setup-zmk
      - /templates
      - /test
    schedule:
      interval: daily
