name: Setup Zephyr toolchain
description: Set up West and Zephyr SDK using Nix

inputs:
  flake:
    description:
      "Absolute path to directory containing flake.nix (if unspecified uses the
      one provided by the action)"
    type: string
    required: false

  toolchain:
    description: "Zephyr toolchain to use (defaults to 'gnuarmemb')."
    type: choice
    required: false
    default: default
    options:
      - default
      - gnuarmemb
      - zephyr
      - zephyr-full

runs:
  using: composite
  steps:
    - name: Get flake
      shell: bash
      run: |
        # Manually default ${{ inputs.flake }} to ${{ github.action_path }}. This is
        # to shield against bug where ${{ github.action_path }} is set incorrect in
        # containers (https://github.com/actions/runner/issues/716.) Normally we don't
        # expect to run this action in a container but no harm in being safe.
        if [ -n "${{ inputs.flake }}" ]; then
          echo "flake=${{ inputs.flake }}" >> $GITHUB_ENV
        else
          echo "flake=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
        fi

    - name: Hash flake
      shell: bash
      run: |
        # Manually compute hash because hashFiles doesn't work outside the workspace
        # (https://github.com/actions/toolkit/issues/1035.)
        shopt -s extglob
        flake_hash=$(sha256sum ${{ env.flake }}/flake.@(nix|lock) | sha256sum | sed 's/[[:blank:]].*//')
        echo "flake_hash=${flake_hash}" >> $GITHUB_ENV

    - name: Install nix
      uses: nixbuild/nix-quick-install-action@v31
      with:
        nix_on_tmpfs: true

    - name: Cache nix derivations
      uses: nix-community/cache-nix-action@v6
      with:
        primary-key:
          # nix-${{ runner.os }}-${{ hashFiles(format('{0}/flake.*', env.flake)) }}
          nix-${{ runner.os }}-${{ env.flake_hash }}

        restore-prefixes-first-match: nix-${{ runner.os }}-

        # Purge old caches and garbage collect new one if there wasn't an exact match
        purge: true
        purge-prefixes: nix-${{ runner.os }}-
        purge-created: 0
        purge-primary-key: never
        gc-max-store-size-linux: 0

    - name: Export devShell
      shell: bash
      run:
        ${GITHUB_ACTION_PATH}/nix-develop.sh "${{ env.flake }}#${{ inputs.toolchain }}"
