name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@v4
    with:
      # Choose from 'zephyr' (Zephyr SDK), 'gnuarmemb' (GNU Arm Embedded), or
      # 'zephyr-full' (Zephyr SDK with full Python toolchain). Defaults to
      # 'zephyr' if omitted. Set to 'gnuarmemb' for slightly better performance
      # at a (small) risk of reduced compatibility. Set to `zephyr-full` for
      # ZMK Studio support.
      toolchain: zephyr
