name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@v4
    with:
      # Defaults to 'zephyr' (Zephyr SDK). Set to 'gnuarmemb' for slightly
      # better performance at a (small) risk of reduced compatibility.
      toolchain: zephyr
