name: Run tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 0,3" # Run every Sunday and Wednesday at 21:00 UTC

jobs:
  test:
    uses: urob/zmk-actions/.github/workflows/run-tests.yml@v7.2.0
    with:
      toolchain: gnuarmemb
      zmk-version: main
