#!/usr/bin/env bash

if [[ -n $(git status --porcelain) ]]; then
  echo "Uncommitted changes detected. Please commit or stash them before proceeding."
  exit 1
fi

OLD_VERSION=$(cat VERSION)
NEW_VERSION="v$1"
echo "${NEW_VERSION}" > VERSION

echo "Bumping version from $OLD_VERSION to $NEW_VERSION"
git ls-files | xargs sed -i "s|\(urob/zmk-actions/[^ ]*\)@${OLD_VERSION}|\1@${NEW_VERSION}|g"
git --no-pager diff

read -p "Do you want to proceed? [y/N] " answer
if [[ "$answer" =~ ^[Yy]$ ]]; then
  echo "Proceeding..."
else
  echo "Aborted."
  exit 1
fi

git add .
git commit -m "Bump to $NEW_VERSION"
git checkout -b releases/${NEW_VERSION%%.*}
git tag ${NEW_VERSION}
git tag -f ${NEW_VERSION%.*}
git tag -f ${NEW_VERSION%%.*}

git checkout main

echo "Done. To push run:"
echo "git push main ${NEW_VERSION%%.*} && git push --tags"
